name: gh pages publish

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
        with:
          repository: quadra-network/canvaswap-libs
          token: ${{secrets.ACCESS_TOKEN}}
          path: canvaswap-libs

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: publish package
        run: |
          cd main
          sudo chown -R $USER:$USER ${{ github.workspace }}
          yarn
          sudo chmod +x sedcommands-polygon.sh
          sudo ./sedcommands-polygon.sh
          git config user.name "itissandeep98"
          git config user.email "itissandeep98@gmail.com"
          git remote set-url origin https://quadra-network:${{secrets.ACCESS_TOKEN}}@github.com/quadra-network/canvaswap
          yarn deploy
